### ISSUE TITLE
Target fails with a SCHEMA containing an object node with null fields

### ISSUE THREAD

**Issue by chrishenry** [adswerve/target-bigquery#32]
### Issue Description

When running the meltano elt command, target crashes with `min() arg is an empty sequence` in the [`prioritize_one_data_type_from_multiple_ones_in_any_of` function](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/schema.py#L150) when a property with type null sub-properties.

For example;
```json
"meta": {
  "type": ["object", "null"],
  "properties": {
    "new_status": {
      "type": ["integer", "null"]
    },
    "previous_status": {
      "type": ["integer", "null"]
    },
    "new_assignee": {
      "type": ["integer", "null"]
    },
    "previous_assignee": {
      "type": ["integer", "null"]
    },
    "new_due_date": {
      "type": ["date-time", "null"]
    },
    "previous_due_date": {
      "type": ["date-time", "null"]
    }
  }
},
```

Snippet from [tap-hellobaton activity stream schema](https://github.com/chrishenry/tap-hellobaton/blob/main/tap_hellobaton/schemas/activity.json)

Relevant log snippet, with additional logging added by me.

```
2022-03-27T22:38:45.870296Z [info     ] INFO activity schema: {'properties': {'id': {'type': 'integer'}, '_self': {'type': 'string'}, 'type': {'type': ['string', 'null']}, 'group': {'type': ['string', 'null']}, 'parent': {'type': ['string', 'null']}, 'child': {'type': ['string', 'null']}, 'actor': {'type': ['string', 'null']}, 'project': {'type': 'string'}, 'parent_type': {'type': ['string', 'null']}, 'child_type': {'type': ['string', 'null']}, 'meta': {'properties': {'new_status': {'type': ['integer', 'null']}, 'previous_status': {'type': ['integer', 'null']}, 'new_assignee': {'type': ['integer', 'null']}, 'previous_assignee': {'type': ['integer', 'null']}, 'new_due_date': {'type': ['date-time', 'null']}, 'previous_due_date': {'type': ['date-time', 'null']}}, 'type': ['object', 'null']}, 'created': {'format': 'date-time', 'type': 'string'}, 'modified': {'format': 'date-time', 'type': 'string'}}} cmd_type=loader job_id=2022-03-27T223842--tap-hellobaton--target-bigquery name=target-bigquery run_id=8bfc1021-3619-4904-8258-16cdced738f4 stdio=stderr
2022-03-27T22:38:45.872988Z [info     ] WARNING force_fields: {}       cmd_type=loader job_id=2022-03-27T223842--tap-hellobaton--target-bigquery name=target-bigquery run_id=8bfc1021-3619-4904-8258-16cdced738f4 stdio=stderr
2022-03-27T22:38:45.873277Z [info     ] WARNING Prioritze: field_property {'anyOf': []} cmd_type=loader job_id=2022-03-27T223842--tap-hellobaton--target-bigquery name=target-bigquery run_id=8bfc1021-3619-4904-8258-16cdced738f4 stdio=stderr
2022-03-27T22:38:45.873403Z [info     ] WARNING Prioritze: anyOf {}    cmd_type=loader job_id=2022-03-27T223842--tap-hellobaton--target-bigquery name=target-bigquery run_id=8bfc1021-3619-4904-8258-16cdced738f4 stdio=stderr
2022-03-27T22:38:45.873637Z [info     ] CRITICAL min() arg is an empty sequence cmd_type=loader job_id=2022-03-27T223842--tap-hellobaton--target-bigquery name=target-bigquery run_id=8bfc1021-3619-4904-8258-16cdced738f4 stdio=stderr
```

I also tried using `force_fields` in `target-tables-config.json`

### Expected behaviour

Target should succeed, creating a subrecord with any non-null values.

**Comment by zvizdo** [comment]
Looked at this. The fix can be reviewed in PR #33.

@chrishenry's issue is that as per JSON Schema standards type date-time doesn't exist, instead, the proper way would be to do:
```json
"new_due_date": {
  "type": ["string", "null"],
  "format": "date-time"
}
```

However, due to simplicity reasons, I think it's reasonable to allow date-time as a standalone type since it does show up in taps out in the wild.

@woochica's issue is related but more tricky. It has to do with arrays without real definitions:
```json
"members": {
  "type": "array"
}
```
As per JSON Schema standards type=array should have an accompanying items key that describes the array elements/items:
```json
"members": {
  "type": "array",
  "items": {
    "type": "string"
  }
}
```

Without items key the conversion code has no way of knowing what type of array to create. So this could legitimately be categorized as an invalid schema, but I think in this case it makes sense to assume a default state.
If we see a field of type array with no other information, we can default to array of strings, which is likely what the source tap's data would look like.

This is more of a let's make something work with bare minimum information, however, it would always be recommended to further define the schema more precisely.

**Comment by RuslanBergenov** [comment]
The fix has been released.

**Comment by woochica** [comment]
Thanks @zvizdo and @RuslanBergenov for taking time to looking into and fixing this issue.

I've just upgraded to the fixed version, but I still get the very same exception. However it shows another schema this time:

```
2022-04-11T16:00:41.176684Z [info     ] INFO time_entries schema: {'properties': {'id': {'type': 'string'}, 'task': {'properties': {'id': {'type': 'string'}, 'name': {'type': 'string'}, 'status': {'properties': {'status': {'type': 'string'}, 'color': {'type': 'string'}, 'type': {'type': 'string'}, 'orderindex': {'type': 'integer'}}, 'type': 'object'}, 'custom_type': {'type': 'null'}}, 'type': 'object'}, 'wid': {'type': 'string'}, 'user': {'properties': {'id': {'type': 'integer'}, 'username': {'type': 'string'}, 'email': {'type': 'string'}, 'color': {'type': 'string'}, 'initials': {'type': 'string'}, 'profilePicture': {'type': 'null'}}, 'type': 'object'}, 'billable': {'type': 'boolean'}, 'start': {'type': 'string'}, 'end': {'type': 'string'}, 'duration': {'type': 'string'}, 'description': {'type': 'string'}, 'tags': {'type': 'array'}, 'source': {'type': 'string'}, 'at': {'type': 'string'}, 'task_location': {'properties': {'list_id': {'type': 'string'}, 'folder_id': {'type': 'string'}, 'space_id': {'type': 'string'}}, 'type': 'object'}, 'task_url': {'type': 'string'}}, 'type': 'object'} cmd_type=loader job_id=2022-04-11T155959--tap-clickup--target-bigquery name=target-bigquery run_id=8c114297-c0c5-4b72-b247-865a883ba82d stdio=stderr
2022-04-11T16:00:41.187190Z [info     ] CRITICAL min() arg is an empty sequence cmd_type=loader job_id=2022-04-11T155959--tap-clickup--target-bigquery name=target-bigquery run_id=8c114297-c0c5-4b72-b247-865a883ba82d stdio=stderr
2022-04-11T16:00:41.191777Z [info     ] CRITICAL ['Traceback (most recent call last):\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/process.py", line 66, in process\n    for s in handler.handle_schema_message(msg):\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/processhandler.py", line 147, in handle_schema_message\n    for s in super(LoadJobProcessHandler, self).handle_schema_message(msg):\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/processhandler.py", line 90, in handle_schema_message\n    schema = build_schema(schema=schema_simplified,\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 369, in build_schema\n    next_field = build_field(field_name, field_property)\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 325, in build_field\n    processed_subfields.append(build_field(subfield_name, subfield_property))\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 296, in build_field\n    field_type = convert_field_type(field_property)\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 175, in convert_field_type\n    prioritized_data_type = prioritize_one_data_type_from_multiple_ones_in_any_of(field_property)\n', '  File "/Users/apple/Dev/bps_meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 150, in prioritize_one_data_type_from_multiple_ones_in_any_of\n    return min(any_of_data_types, key=any_of_data_types.get)\n', 'ValueError: min() arg is an empty sequence\n'] cmd_type=loader job_id=2022-04-11T155959--tap-clickup--target-bigquery name=target-bigquery run_id=8c114297-c0c5-4b72-b247-865a883ba82d stdio=stderr
```

**Comment by zvizdo** [comment]
Thanks for following up here @woochica!

The issue is a few of the properties are defined as null, like below:
```json
"profilePicture": {
  "type": "null"
}
```

This is an obvious problem because now we have no idea what the data type should be in BigQuery. And even, why is something defined as type=null?

@RuslanBergenov what are your throughs on this?
We could potentially treat all the above situations as just nullable string field in BigQuery.

**Comment by matotias** [comment]
I encountered a similar issue while using meltano from [tap-postgres](https://github.com/transferwise/pipelinewise-tap-postgres) to this target if I have a `jsonb` column. 
The error I get is this:

```
2022-04-13T03:56:12.388071Z [info     ] CRITICAL 'RECORD'              cmd_type=loader job_id=dwh-to-bigquery name=target-bigquery run_id=057e8d81-8d17-4f8d-9b94-6dd4a99a1b6f stdio=stderr
2022-04-13T03:56:12.391491Z [info     ] CRITICAL ['Traceback (most recent call last):\n', '  File "/Users/matotias/Development/singer-tests/bigquery-backups/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/Users/matotias/Development/singer-tests/bigquery-backups/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/process.py", line 54, in process\n    for s in handler.handle_record_message(msg):\n', '  File "/Users/matotias/Development/singer-tests/bigquery-backups/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/processhandler.py", line 179, in handle_record_message\n    nr = format_record_to_schema(nr, self.bq_schema_dicts[stream])\n', '  File "/Users/matotias/Development/singer-tests/bigquery-backups/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 359, in format_record_to_schema\n    record[k] = conversion_dict[bq_schema[k]["type"]](v)\n', "KeyError: 'RECORD'\n"] cmd_type=loader job_id=dwh-to-bigquery name=target-bigquery run_id=057e8d81-8d17-4f8d-9b94-6dd4a99a1b6f stdio=stderr
``` 

I see the error even when excluding that column, the only way I could make it work was to remove the column from the origin table.

**Comment by RuslanBergenov** [comment]
@woochica, I agree with @zvizdo that this part of JSON schema below is not valid. We recommend specifying the schema in `tap-catalog.json` file and supplying this file during as an argument during the sync. 

```
"profilePicture": {
  "type": "null"
}
```

**Comment by RuslanBergenov** [comment]
@zvizdo , re: We could potentially treat all the above situations as just nullable string field in BigQuery.

I like this idea, Meltano community recommends such a failsafe as a best practice: https://github.com/MeltanoLabs/Singer-Working-Group/issues/20

**Comment by chrishenry** [comment]
Hey @RuslanBergenov & @zvizdo, thanks so much for your feedback and hard work on this! I've updated and confirmed my schema is cleanly importing into BigQuery.
